In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 
import xlrd
import time

ModuleNotFoundError: No module named 'numpy.testing.decorators'

In [ ]:
import csv
def csv_reader(path):
    with open(path, 'r', encoding='utf-8') as fp:
        reader = csv.reader(fp)
        data = [i for i in reader]
    return data
def csv_writer(path, header, data):
    with open(path, 'w', encoding='utf-8', newline="") as csvfile:
        writer = csv.writer(csvfile, delimiter=',')
        writer.writerow(header)
        writer.writerows(data)

In [11]:
df = pd.read_excel('./PASSENGER_RECORD.xlsx')

In [12]:
df.columns

Index(['PR_ID', 'PPID', 'TRAIN_TYPE', 'TRAIN_CODE', 'BOARD_DATE', 'BOARD_TIME',
       'ARRIVAL_DATE', 'ARRIVAL_TIME', 'START_STA', 'ARRIVAL_STA',
       'TRAVEL_TIME', 'TRAVEL_LENGTH', 'SEAT_TYPE', 'COACH_NO', 'SEAT_NO',
       'BUYYER_PID'],
      dtype='object')

车厢号、座位号、座位类别参考意义不大，直接drop

In [13]:
df = df.drop(['TRAIN_TYPE','TRAIN_CODE','COACH_NO','SEAT_NO','SEAT_TYPE'], axis=1)
df.columns

Index(['PR_ID', 'PPID', 'BOARD_DATE', 'BOARD_TIME', 'ARRIVAL_DATE',
       'ARRIVAL_TIME', 'START_STA', 'ARRIVAL_STA', 'TRAVEL_TIME',
       'TRAVEL_LENGTH', 'BUYYER_PID'],
      dtype='object')

BOARD_DATE、BOARD_TIME日期和时间是分离的，把它们合并到同一列上，ARRIVAL同理

In [5]:
df['BOARD_TIME'] = df['BOARD_DATE'] + df['BOARD_TIME'].apply(str).apply(pd.Timedelta)
df = df.drop(['BOARD_DATE'], axis=1)
df['BOARD_TIME']

0        2012-03-08 19:04:00
1        2012-03-12 08:01:00
2        2012-03-12 18:42:00
3        2012-03-01 08:03:00
4        2012-03-01 20:13:00
                 ...
985754   2012-05-04 03:21:00
985755   2012-05-21 17:07:00
985756   2012-05-26 18:37:00
985757   2012-06-19 12:44:00
985758   2012-06-04 11:59:00
Name: BOARD_TIME, Length: 985759, dtype: datetime64[ns]

In [6]:
# ARRIVAL虽然看上去和BOARD一样，但实际上读取到的类型是datetime.time，所以做一个特殊的parser来处理，不能直接apply(str)
parser = lambda time : time.strftime('%H:%M:%S')
df['ARRIVAL_TIME'] = df['ARRIVAL_DATE'] + df['ARRIVAL_TIME'].apply(parser).apply(pd.Timedelta)
df = df.drop(['ARRIVAL_DATE'], axis=1)
df['ARRIVAL_TIME']

0        2012-03-08 20:04:00
1        2012-03-12 09:01:00
2        2012-03-12 19:42:00
3        2012-03-01 09:03:00
4        2012-03-01 21:13:00
                 ...
985754   2012-05-04 03:21:00
985755   2012-05-21 19:07:00
985756   2012-05-27 02:37:00
985757   2012-06-19 12:44:00
985758   2012-06-04 17:59:00
Name: ARRIVAL_TIME, Length: 985759, dtype: datetime64[ns]

In [7]:
df.groupby('PPID')['TRAVEL_LENGTH'].describe()

,count,mean,std,min,25%,50%,75%,max
PPID,,,,,,,,
110103195807011008,56.0,670.714286,746.941198,0.0,89.00,268.5,1209.75,2343.0
110105196708252992,50.0,662.000000,397.694068,40.0,269.50,738.0,964.00,1241.0
110108195508280000,45.0,580.288889,408.452268,0.0,300.00,499.0,796.00,1408.0
110222199103150000,426.0,175.469484,132.810773,19.0,154.00,154.0,154.00,2420.0
110224198701275008,457.0,226.719912,267.501755,20.0,154.00,154.0,154.00,1691.0
...,...,...,...,...,...,...,...,...
65312419920615332X,43.0,281.395349,273.697708,0.0,6.00,266.0,426.00,1428.0
65412119900226066X,614.0,132.724756,141.314434,0.0,65.00,123.0,140.00,1537.0
65412319911204248X,56.0,331.625000,237.186659,3.0,138.75,299.0,472.75,946.0
65420119940522003X,41.0,403.975610,359.110323,14.0,117.00,277.0,694.00,1132.0
65432419920413002X,405.0,188.558025,160.842783,6.0,154.00,154.0,154.00,1961.0

In [8]:
df['BOARD_TIME'].max() - df['BOARD_TIME'].min()

Timedelta('361 days 23:57:00')

数据为11076名乘客一年内的购票记录

In [10]:
bins = np.linspace(df['TRAVEL_LENGTH'].min(), df['TRAVEL_LENGTH'].max(), 15)
travel_length_cat = pd.cut(df['TRAVEL_LENGTH'], bins)
travel_length_cat.value_counts().plot(kind='bar')

(0.0, 231.357]          612835
(231.357, 462.714]      150576
(462.714, 694.071]       80667
(694.071, 925.429]       66871
(925.429, 1156.786]      36337
(1156.786, 1388.143]     16334
(1388.143, 1619.5]        6944
(1619.5, 1850.857]        4255
(2082.214, 2313.571]      2428
(1850.857, 2082.214]      1960
(3007.643, 3239.0]         577
(2313.571, 2544.929]       526
(2776.286, 3007.643]       203
(2544.929, 2776.286]       132
Name: TRAVEL_LENGTH, dtype: int64

- 出发站、到达站的填充：可以用列车编号、到达站（出发站）、运行时间完全相同的数据来填充
- 百度地图API转经纬度
- DBSCAN Isolation Forest

- 乘车时间间隔（设置阈值划分长途和短途）
- 乘车频率（可以按月统计）
- Num of boarding stations（可以看最常去的所占的比例）
- 夜间乘车次数
- 座位种类

In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 
import xlrd
import time

In [21]:
# start processing
df = pd.read_excel('./PASSENGER_RECORD.xlsx')
# # convert .xlsx file to .csv file for easy loading. Simply use MS Excel 'save as' function. 
# df = pd.read_csv('./PASSENGER_RECORD.csv')

In [115]:
df

,PR_ID,PPID,TRAIN_TYPE,TRAIN_CODE,BOARD_DATE,BOARD_TIME,ARRIVAL_DATE,ARRIVAL_TIME,START_STA,ARRIVAL_STA,TRAVEL_TIME,TRAVEL_LENGTH,SEAT_TYPE,COACH_NO,SEAT_NO,BUYYER_PID
0,236365,210302199212143008,D,D15,2012-03-08,19:04:00,2012-03-08,20:04:00,盘锦北,沈阳北,01:00:00,154,GD,4,79,210302199212143008
1,236366,210302199212143008,D,D22,2012-03-12,08:01:00,2012-03-12,09:01:00,沈阳北,盘锦北,01:00:00,154,GD,13,87,210302199212143008
2,236367,210302199212143008,D,D102,2012-03-12,18:42:00,2012-03-12,19:42:00,盘锦北,沈阳北,01:00:00,154,GD,12,21,210302199212143008
3,236368,210302199212143008,D,D164,2012-03-01,08:03:00,2012-03-01,09:03:00,沈阳北,盘锦北,01:00:00,154,GD,6,19,210302199212143008
4,236369,210302199212143008,O,1052,2012-03-01,20:13:00,2012-03-01,21:13:00,盘锦北,沈阳北,01:00:00,154,YZ,11,51,210302199212143008
5,236370,210302199212143008,D,D102,2012-03-16,09:42:00,2012-03-16,10:42:00,沈阳北,盘锦北,01:00:00,154,GD,5,53,210302199212143008
6,236371,210302199212143008,D,D12,2012-03-16,18:59:00,2012-03-16,19:59:00,盘锦北,沈阳北,01:00:00,154,GD,7,53,210302199212143008
7,236372,210302199212143008,O,Z194,2012-03-18,09:23:00,2012-03-18,10:23:00,沈阳北,盘锦北,01:00:00,154,ZP,2,86,210302199212143008
8,236373,210302199212143008,D,D102,2012-03-18,19:04:00,2012-03-18,20:04:00,盘锦北,沈阳北,01:00:00,154,GD,16,28,210302199212143008
9,236374,210302199212143008,D,D164,2012-03-15,09:00:00,2012-03-15,10:00:00,沈阳北,盘锦北,01:00:00,154,GD,7,76,210302199212143008
10,236375,210302199212143008,D,D16,2012-03-15,18:41:00,2012-03-15,19:41:00,盘锦北,沈阳北,01:00:00,154,GD,4,84,210302199212143008
11,236376,210302199212143008,D,D7,2012-03-14,08:10:00,2012-03-14,09:10:00,沈阳北,盘锦北,01:00:00,154,GD,3,42,210302199212143008
12,236377,210302199212143008,D,D17,2012-03-14,19:49:00,2012-03-14,20:49:00,盘锦北,沈阳北,01:00:00,154,GD,6,56,210302199212143008
13,235773,21148119920321721X,D,D26,2012-08-15,17:34:00,2012-08-15,18:34:00,盘锦北,沈阳北,01:00:00,154,GD,2,44,21148119920321721X
14,235774,21148119920321721X,D,D102,2012-08-16,09:49:00,2012-08-16,10:49:00,沈阳北,盘锦北,01:00:00,154,GD,4,74,21148119920321721X
15,235775,21148119920321721X,D,D15,2012-08-16,19:43:00,2012-08-16,20:43:00,盘锦北,沈阳北,01:00:00,154,GD,10,22,21148119920321721X
16,235776,21148119920321721X,D,D102,2012-08-21,09:16:00,2012-08-21,10:16:00,沈阳北,盘锦北,01:00:00,154,GD,16,26,21148119920321721X
17,235777,21148119920321721X,D,D12,2012-08-21,19:34:00,2012-08-21,20:34:00,盘锦北,沈阳北,01:00:00,154,GD,10,23,21148119920321721X
18,235778,21148119920321721X,O,K518,2012-08-09,08:10:00,2012-08-09,09:10:00,沈阳北,盘锦北,01:00:00,154,YZ,14,38,21148119920321721X
19,235779,21148119920321721X,D,D102,2012-08-09,20:42:00,2012-08-09,21:42:00,盘锦北,沈阳北,01:00:00,154,GD,2,76,21148119920321721X
20,235780,21148119920321721X,D,D7,2012-08-08,09:32:00,2012-08-08,10:32:00,沈阳北,盘锦北,01:00:00,154,GD,7,20,21148119920321721X
21,235781,21148119920321721X,D,D7,2012-08-08,20:34:00,2012-08-08,21:34:00,盘锦北,沈阳北,01:00:00,154,GD,11,71,21148119920321721X
22,235782,21148119920321721X,D,D7,2012-08-01,09:59:00,2012-08-01,10:59:00,沈阳北,盘锦北,01:00:00,154,GD,1,81,21148119920321721X
23,235783,21148119920321721X,D,D102,2012-08-01,19:51:00,2012-08-01,20:51:00,盘锦北,沈阳北,01:00:00,154,GD,16,5,21148119920321721X
24,235784,21148119920321721X,D,D12,2012-08-04,09:23:00,2012-08-04,10:23:00,沈阳北,盘锦北,01:00:00,154,GD,3,19,21148119920321721X
25,235785,21148119920321721X,O,K518,2012-08-04,17:01:00,2012-08-04,18:01:00,盘锦北,沈阳北,01:00:00,154,YZ,15,66,21148119920321721X
26,235786,21148119920321721X,D,D22,2012-09-23,09:59:00,2012-09-23,10:59:00,沈阳北,盘锦北,01:00:00,154,GD,3,50,21148119920321721X
27,235787,21148119920321721X,D,D27,2012-09-23,20:49:00,2012-09-23,21:49:00,盘锦北,沈阳北,01:00:00,154,GD,2,18,21148119920321721X
28,235788,21148119920321721X,D,D7,2012-09-12,08:51:00,2012-09-12,09:51:00,沈阳北,盘锦北,01:00:00,154,GD,7,78,21148119920321721X
29,236547,210302199212143008,D,D9,2012-08-26,19:20:00,2012-08-26,20:20:00,盘锦北,沈阳北,01:00:00,154,GD,5,4,210302199212143008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985729,768309,210282199203140000,O,K95,2012-12-06,14:28:00,2012-12-06,18:28:00,北京,盘锦,04:00:00,594,RZ,12,52,210282199203140000
985730,768310,210282199203140000,D,D16,2012-12-10,12:46:00,2012-12-10,17:46:00,北京,沈阳北,05:00:00,703,GD,7,38,210282199203140000
985731,768311,210282199203140000,D,D26,2012-12-24,21:24:00,2012-12-24,23:24:00,北京,北戴河,02:00:00,277,GD,6,89,210282199203140000
985732,768312,210282199203140000,D,D9,2012-12-21,03:57:00,2012-12-21,08:57:00,北京,沈阳北,05:00:00,703,GD,15,77,210282199203140000
985733,768313,210282199203140000,O,T188,2012-12-03,01:21:00,2012-12-03,02:21:00,葫芦岛,盘锦,01:00:00,145,YZ,10,18,210282199203140000
985734,768314,210282199203140000,D,D9,2012-12-23,09:46:00,2012-12-23,14:46:00,北京,台安,05:00:00,604,GD,6,28,210282199203140000
985735,768315,211103199402110016,O,K7369,2012-01-24,12:46:00,2012-01-24,20:46:00,营口,苇子沟,08:00:00,1024,RZ,12,84,211103199402110016
985736,768316,211103199402110016,O,4229,2012-01-15,10:41:00,2012-01-15,10:41:00,营口,辽阳,00:00:00,115,ZP,4,45,211103199402110016
985737,768317,211103199402110016,O,K7369,2012-01-03,16:48:00,2012-01-03,17:48:00,沈阳,营口,01:00:00,179,ZP,1,55,211103199402110016
985738,768318,211103199402110016,O,4229,2012-01-10,16:43:00,2012-01-10,16:43:00,海城,营口,00:00:00,54,ZP,12,11,211103199402110016
985739,768319,211103199402110016,O,K7369,2012-01-19,11:14:00,2012-01-19,16:14:00,吉林,营口,05:00:00,643,RZ,13,90,211103199402110016
985740,768320,211103199402110016,O,K7369,2012-02-10,13:53:00,2012-02-10,14:53:00,营口,林盛堡,01:00:00,154,YZ,7,17,211103199402110016
985741,768321,211103199402110016,D,D19,2012-02-27,03:31:00,2012-02-27,07:31:00,沈阳北,滦县,04:00:00,495,GD,6,1,211103199402110016
985742,768322,211103199402110016,D,D8034,2012-03-16,08:35:00,2012-03-16,08:35:00,长春,公主岭南,00:00:00,75,GD,13,34,211103199402110016
985743,768323,211103199402110016,O,K7369,2012-03-25,10:48:00,2012-03-25,10:48:00,老边,营口,00:00:00,11,YZ,16,71,211103199402110016
985744,768324,211103199402110016,O,K7369,2012-03-06,02:50:00,2012-03-06,03:50:00,林盛堡,营口,01:00:00,154,YZ,16,34,211103199402110016
985745,768325,211103199402110016,O,K7369,2012-03-27,10:57:00,2012-03-27,10:57:00,营口,大石桥,00:00:00,22,ZP,9,2,211103199402110016
985746,768326,211103199402110016,O,K7369,2012-04-05,03:25:00,2012-04-05,07:25:00,营口,磐石,04:00:00,499,ZP,3,80,211103199402110016
985747,768327,211103199402110016,O,K7369,2012-04-02,17:40:00,2012-04-02,19:40:00,营口,抚顺北,02:00:00,244,ZP,11,28,211103199402110016
985748,768328,211103199402110016,O,K7369,2012-04-10,18:21:00,2012-04-11,02:21:00,营口,延吉,08:00:00,992,RZ,5,77,211103199402110016
985749,768329,211103199402110016,O,K7369,2012-04-14,11:24:00,2012-04-14,12:24:00,苏家屯,营口,01:00:00,163,ZP,8,37,211103199402110016
985750,768330,211103199402110016,O,K7369,2012-04-15,14:13:00,2012-04-15,14:13:00,大石桥,营口,00:00:00,22,RZ,1,68,211103199402110016
985751,768331,211103199402110016,O,4229,2012-04-23,16:32:00,2012-04-23,17:32:00,苏家屯,营口,01:00:00,163,YZ,7,54,211103199402110016
985752,768332,211103199402110016,O,K7369,2012-05-15,15:02:00,2012-05-15,22:02:00,营口,安图,07:00:00,926,RZ,2,5,211103199402110016
985753,768333,211103199402110016,O,K7369,2012-05-16,16:14:00,2012-05-16,21:14:00,吉林,营口,05:00:00,643,RZ,16,58,211103199402110016
985754,768334,211103199402110016,O,4229,2012-05-04,03:21:00,2012-05-04,03:21:00,辽阳,营口,00:00:00,115,YZ,5,36,211103199402110016
985755,768335,211103199402110016,O,K7369,2012-05-21,17:07:00,2012-05-21,19:07:00,营口,抚顺北,02:00:00,244,RZ,5,54,211103199402110016
985756,768336,211103199402110016,O,K7369,2012-05-26,18:37:00,2012-05-27,02:37:00,苇子沟,营口,08:00:00,1024,ZP,9,72,211103199402110016
985757,768337,211103199402110016,O,K7369,2012-06-19,12:44:00,2012-06-19,12:44:00,鞍山,营口,00:00:00,90,RZ,16,72,211103199402110016
985758,768338,211103199402110016,O,K7369,2012-06-04,11:59:00,2012-06-04,17:59:00,营口,蛟河,06:00:00,740,YZ,15,74,211103199402110016

In [ ]:
# ['PR_ID', 'PPID'1, 'TRAIN_TYPE'1, 'TRAIN_CODE'1, 'BOARD_DATE', 'BOARD_TIME',
#        'ARRIVAL_DATE', 'ARRIVAL_TIME', 'START_STA'1, 'ARRIVAL_STA'1,
#        'TRAVEL_TIME', 'TRAVEL_LENGTH', 'SEAT_TYPE'1, 'COACH_NO', 'SEAT_NO',
#        'BUYYER_PID'1]

# Simple token features we use in our project are:
1. Passenger. PPID
    - Format: a integer indicates passenger id
2. Buyyer. BUYYER_PID
    - Format: a integer indicates buyyer id
3. Start Stations.  START_STA
    - Format: a integer indicates No. of Start Station
4. Arrival Stations.  ARRIVAL_STA
    - Format: a integer indicates No. of Arrival Station
5. Train Code. TRAIN_CODE
    - Format: a integer
6. Train Type. TRAIN_TYPE
    - Format: a integer
7. Seat type. SEAT_TYPE
    - Format: a integer

In [4]:
simple_feature2idx = {'PPID':{},
                      'BUYYER_PID':{}, 
                      'START_STA':{}, 
                      'ARRIVAL_STA':{}, 
                      'TRAIN_CODE':{}, 
                      'TRAIN_TYPE':{}, 
                      'SEAT_TYPE':{}}

In [5]:
# set look-up table
for feature in simple_feature2idx.keys():
    print("processing: {}".format(feature))
    df[feature] = df[feature].apply(str)
    for value in df[feature].apply(str).tolist():
        if value not in simple_feature2idx[feature]:
            simple_feature2idx[feature][value] = len(simple_feature2idx[feature])

processing: PPID
processing: BUYYER_PID
processing: START_STA
processing: ARRIVAL_STA
processing: TRAIN_CODE
processing: TRAIN_TYPE
processing: SEAT_TYPE

In [6]:
def tokenize_feature(all_features, feature2idx):
    index_list = [feature2idx[feat] for feat in all_features] 
    feature_vector = np.array(index_list)
    print(feature_vector.shape)
    return feature_vector

In [119]:
# set look-up table
simple_feature_vectors = {}
for feature in simple_feature2idx.keys():
    simple_feature_vectors[feature] = tokenize_feature(df[feature].apply(str).tolist(), simple_feature2idx[feature])
simple_feature_vectors['START_STA'] = tokenize_feature(df['START_STA'].apply(str).tolist(), simple_feature2idx['START_STA'])
simple_feature_vectors['ARRIVAL_STA'] = tokenize_feature(df['ARRIVAL_STA'].apply(str).tolist(), simple_feature2idx['START_STA'])

(985759,)
(985759,)
(985759,)
(985759,)
(985759,)
(985759,)
(985759,)
(985759,)
(985759,)

# Simple digit features we use in our project are:
1. Tranvel Time. TRAVEL_TIME
    - Format: a integer represent hours   
1. Tranvel Length. TRAVEL_LENGTH
    - Format: a integer represent distances   
3. Board Date.  BOARD_DATE
    - Format: a integer represent num of days after 2012/01/01 when boarding. 比如2012年1月2号就是1，2月15日就是30+15=45
4. Board Time. BOARD_TIME
    - Format: a interger represent num minutes from 0:0:0. 比如当日4点15分就是4*60+15=255
5. Arrival Date.  ARRIVAL_DATE
    - Format: a integer represent num of days after 2012/01/01 when boarding. 比如2012年1月2号就是1，2月15日就是30+15=45
6. Arrival Time.  ARRIVAL_TIME
    - Format: a interger represent num minutes from 0:0:0. 比如当日4点15分就是4*60+15=255
7. Seat Number.  SEAT_NO
    - Format: a integer 
8. Coach Number.  COACH_NO
    - Format: a integer

In [8]:
digit_feature2idx = {'TRAVEL_TIME':{},
                     'TRAVEL_LENGTH':{},
                     'BOARD_DATE':{}, 
                     'BOARD_TIME':{}, 
                     'ARRIVAL_DATE':{}, 
                     'ARRIVAL_TIME':{}, 
                     'SEAT_NO':{}, 
                     'COACH_NO':{}}

In [9]:
digit_feature_vectors = {}
for feature in digit_feature2idx.keys():
    if feature in ['TRAVEL_LENGTH', 'SEAT_NO', 'COACH_NO']:
        index_list = df[feature].apply(int).tolist()
        feature_vector = np.array(index_list)
        print("{}\t{}".format(feature, feature_vector.shape))
        digit_feature_vectors[feature] = feature_vector

TRAVEL_LENGTH	(985759,)
SEAT_NO	(985759,)
COACH_NO	(985759,)

In [10]:
# feature_vector = np.array([int(item.split(':')[0]) for item in df['TRAVEL_TIME'].apply(str).tolist()])
# print("{}\t{}".format('TRAVEL_TIME', feature_vector.shape))
# digit_feature_vectors['TRAVEL_TIME'] = feature_vector

ValueError: invalid literal for int() with base 10: '1900-01-01 02'

In [23]:
# board_times = pd.to_datetime((df['BOARD_DATE'].apply(str) +' ' + df['BOARD_TIME'].apply(str)), format='%m/%d/%Y %H:%M:%S')
# for row_idx, item in enumerate(df['ARRIVAL_TIME'].apply(str).tolist()):
#     if item[:2]=='25' or item[:2]=='24':
#         df['ARRIVAL_TIME'][row_idx] = '23'+item[2:]
# arrival_times = pd.to_datetime((df['ARRIVAL_DATE'] +' ' + df['ARRIVAL_TIME'].apply(str)), format='%m/%d/%Y %H:%M:%S')
board_times = df['BOARD_DATE'] + df['BOARD_TIME'].apply(str).apply(pd.Timedelta)
parser = lambda time : time.strftime('%H:%M:%S')
arrival_times = df['ARRIVAL_DATE'] + df['ARRIVAL_TIME'].apply(parser).apply(pd.Timedelta)
initial_timestamp = pd.Timestamp('2012-01-01T00')  # Timestamp('2012-01-01 00:00:00')

feature_vector = np.array((board_times - initial_timestamp).astype('timedelta64[D]').tolist())
print("{}\t{}".format('BOARD_DATE', feature_vector.shape))
digit_feature_vectors['BOARD_DATE'] = feature_vector

feature_vector = np.array([h*60+m for h, m in zip(board_times.dt.hour.tolist(), board_times.dt.minute.tolist())])
print("{}\t{}".format('BOARD_TIME', feature_vector.shape))
digit_feature_vectors['BOARD_TIME'] = feature_vector

feature_vector = np.array((arrival_times - initial_timestamp).astype('timedelta64[D]').tolist())
print("{}\t{}".format('ARRIVAL_DATE', feature_vector.shape))
digit_feature_vectors['ARRIVAL_DATE'] = feature_vector

feature_vector = np.array([h*60+m for h, m in zip(arrival_times.dt.hour.tolist(), arrival_times.dt.minute.tolist())])
print("{}\t{}".format('ARRIVAL_TIME', feature_vector.shape))
digit_feature_vectors['ARRIVAL_TIME'] = feature_vector

BOARD_DATE	(985759,)
BOARD_TIME	(985759,)
ARRIVAL_DATE	(985759,)
ARRIVAL_TIME	(985759,)

In [24]:
len(simple_feature2idx['PPID'])

11076

In [52]:
from collections import Counter

In [62]:
month2days = {0: -1, 1: 30, 2: 59, 3: 90, 4: 120, 5: 151, 6: 181, 7:212, 8:243, 9:273, 10:304, 11:334, 12:365}
days2month = {idx2:idx1 for idx1, idx2 in month2days.items()}

0 PPID

1 BUYYER_PID

2 START_STA

3 ARRIVAL_STA

4 TRAIN_CODE

5 TRAIN_TYPE

6 SEAT_TYPE


7 TRAVEL_LENGTH

8 SEAT_NO

9 COACH_NO

10 BOARD_DATE

11 BOARD_TIME

12 ARRIVAL_DATE

13 ARRIVAL_TIME

# Advanced features we use in our project are 
6. Buyyer is the same with Passenger? BUYYER_PID/PPID  new: SAME_PERSON  
    - Format: a integer 1 or 0

# 讨论后需要的features，以ppid为单位
2. 总乘车次数（按月统计？）NUM_TRIP
1. 最高频率线路占比：通勤（统计每个id的所有站，top2占比？） ROUTE_FREQ
4. 夜间乘车次数（比如定义23:00-5:00属于夜间）NIGHT_TRIP
3. 短时间出行次数（time<3？） SHORT_TRIP
5. 一线城市比例（始发站or终点站）BIG_CITY_FREQ
6. 站票/硬座比例  HARD_SEAT

In [26]:
advanced_feature_vectors = {'NUM_TRIP':[], 'ROUTE_FREQ':[], 'SHORT_TRIP':[], 'NIGHT_TRIP':[], 'BIG_CITY_FREQ':[], 'HARD_SEAT':[]}

In [134]:
all_feature_vectors = np.stack(list(simple_feature_vectors.values()) + 
                               list(digit_feature_vectors.values()), axis=0)
print(all_feature_vectors.shape)

(14, 985759)

In [51]:
passenger_rows_index = {ppid: np.where(simple_feature_vectors['PPID'] == simple_feature2idx['PPID'][ppid]) for ppid in simple_feature2idx['PPID']}

In [87]:
passenger_rows_index_small = {ppid:passenger_rows_index[ppid] for ppid in list(passenger_rows_index.keys())[:5]}

In [168]:
all_final_features = []
for ppid, index in passenger_rows_index.items():
# for ppid, index in passenger_rows_index_small.items():
    index = index[0]
    features = np.zeros(22)
    vectors = all_feature_vectors[:,index]
    num_trip_all = np.array(vectors.shape[1])   # 0
    features[0] = num_trip_all
#     print(features)
    
    # 总乘车次数（按月统计？）NUM_TRIP
    num_trip_monthly = np.zeros(12)   # 1-12
    for month in range(1, 13):
        min_days = month2days[month-1]
        max_days = month2days[month]
        month_trip_index = np.where((max_days>=vectors[10,:]) == (vectors[10,:]>=min_days))[0]
        num_trip_monthly[month-1] = month_trip_index.shape[0]
    features[1:13] = num_trip_monthly
#     print(features)

    # 最高频率线路占比：通勤（统计每个id的所有站，top2占比？） ROUTE_FREQ
    all_routes = [(vectors.astype(np.int)[2, i], vectors.astype(np.int)[3, i]) for i in range(num_trip_all)]
    route_counter = Counter(all_routes)
    num_routes = np.array(len(all_routes))  # 13
    num_most_freq_route = np.array(route_counter.most_common(1)[0][1])  # 14
    try:
        num_second_freq_route = np.array(route_counter.most_common(2)[1][1])  # 15
    except:
        num_second_freq_route = 0
    portion_most_freq_route = np.array(route_counter.most_common(1)[0][1]/num_trip_all)  # 16
    portion_second_freq_route = np.array(num_second_freq_route/num_trip_all)  # 17
    features[13] = num_routes
    features[14] = num_most_freq_route
    features[15] = num_second_freq_route
    features[16] = portion_most_freq_route
    features[17] = portion_second_freq_route
#     print(features)

    # 夜间乘车次数（比如定义23:00-5:00属于夜间）NIGHT_TRIP
    start_night_index = np.where( (vectors[11,:]>23*60) == (vectors[11,:]<5*60))[0]
    num_start_night_index = np.array(start_night_index.shape[0])  # 18
    end_night_index = np.where( (vectors[13,:]>23*60) == (vectors[13,:]<5*60))[0]
    num_end_night_index = np.array(end_night_index.shape[0])  # 19
    features[18] = num_start_night_index
    features[19] = num_end_night_index
#     print(features)

    # 短时间出行次数（time<3？） SHORT_TRIP
    trip_hours = (vectors[13,:] - vectors[11,:])/60 + (vectors[12,:] - vectors[10,:])*24  
    num_short_trip = np.where(trip_hours<3)[0].shape[0]  # 20
    features[20] = num_short_trip
#     print(features)
    
    # 站票/硬座比例 HARD_SEAT
    num_hardseat = np.where(vectors[6,:]==simple_feature2idx['SEAT_TYPE']['YZ'])[0].shape[0]
    portion_hardseat = num_hardseat / num_trip_all  # 21
    features[21] = portion_hardseat
    
    # TODO 一线城市比例（始发站or终点站）BIG_CITY_FREQ
    
    all_final_features.append(features)

In [169]:
all_final_features = np.stack(all_final_features, axis=0)
print(all_final_features.shape)

(11076, 22)

In [170]:
np.save('./feature_vector_v1.npy', all_final_features)